GET http://localhost:8080/contatos HTTP/1.1
Authorization: Basic joao@teste.com 1234


###
POST http://localhost:8080/contatos HTTP/1.1
Authorization: Basic joao@teste.com 1234
Content-Type: application/json

{
    "id": 0,
    "nome": "Joaquina Barborsa",
    "email": "joaquina@teste.com",
    "telefone": "(11) 6666-6666"
}