POST http://localhost:8080/auth/addNewUser HTTP/1.1
Content-Type: application/json

{
    "id" : 0, 
    "name": "Joao Silva",
    "email": "joao@teste.com",
    "password": "123456",
    "roles": "ADMIN"
}


###


POST http://localhost:8080/auth/generateToken HTTP/1.1
Content-Type: application/json

{
    "username": "joao@teste.com",
    "password": "123456"
}