POST http://localhost:8080/auth/addNewUser HTTP/1.1
Content-Type: application/json

{
    "id" : 0, 
    "name": "Maria Silva",
    "email": "maria@teste.com",
    "password": "123456",
    "roles": "ADMIN,USER"
}


###


POST http://localhost:8080/auth/generateToken HTTP/1.1
Content-Type: application/json

{
    "username": "maria@teste.com",
    "password": "123456"
}